spring:
  liquibase:
    enabled: true
    change-log: "classpath:db.changelog/db.changelog-persistence.xml"
    password:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviedigger
    username: vilda
    password: digger
  h2:
    console:
      enabled: true
      path: /h2
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/moviesdigger
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
          user-logout-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/logout

moviesdigger:
  realm-name: moviesdigger
  public-endpoints:
    login: client-api/v1/user/login
    get-access-token: client-api/v1/user/token

keycloak:
  client:
    admin:
      realm: master
      auth-server-url: http://localhost:8080
      client-id: admin-cli
      admin-username: admin
      admin-password: admin
  open-id-connect:
    api:
      token-endpoint: http://localhost:8080/realms/${moviesdigger.realm-name}/protocol/openid-connect/token

#logging application
logging:
  level:
    com.backbase.moviesdigger: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: INFO

server:
  port: 8081