spring:
  liquibase:
    enabled: true
    change-log: "classpath:db.changelog/db.changelog-persistence.xml"
    password:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviedigger
    username: vilda
    password: digger
  h2:
    console:
      enabled: true
      path: /h2

keycloak:
  client:
    admin:
      realm: master
      auth-server-url: http://localhost:8080
      client-id: admin-cli
      admin-username: admin
      admin-password: admin

#logging application
logging:
  level:
    com.backbase.moviesdigger: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: INFO

server:
  port: 8081